version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        environment:
          - KEYCLOAK_USER=user
          - KEYCLOAK_PASSWORD=user
          - KEYCLOAK_ADMIN=admin
          - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
          - "8081:8080"
        volumes:
          - ./realm.json:/tmp/realm.json
        command:
          - start-dev

  app:
    build: .
    container_name: template
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data:

